# Generated by Django 4.0.6 on 2022-07-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_id',
            new_name='user',
        ),
    ]
