# Generated by Django 4.0.6 on 2022-07-11 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.product'),
        ),
    ]
