# Generated by Django 4.0.6 on 2022-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_category_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('TOY', 'Toys'), ('TEC', 'Tech'), ('HOM', 'Home'), ('CLT', 'Clothes'), ('MIS', 'Miscellaneous')], default='MIS', max_length=64),
        ),
    ]
