# Generated by Django 4.0.6 on 2022-07-11 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_start_bid_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watching_users',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
